# Travis CI build file for Kitura-CouchDB.
# Kitura runs on OS X and Linux (Ubuntu v15.10).

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop

notifications:
  slack: ibmswift:RHkwcHYh4kkYVRVzm9nZk5TF

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
    - os: osx
      osx_image: xcode7.2
      sudo: required

before_install:
  - echo "Operating system -> '$TRAVIS_OS_NAME'"
  - echo "Travis build directory -> '$TRAVIS_BUILD_DIR'"
  - git clone https://github.com/IBM-Swift/Kitura-CI.git
  - cp ./Kitura-CI/*.sh .
  - git clone -b master https://$JAZZHUB_USER:$JAZZHUB_PWD@hub.jazz.net/git/milbuild/MIL.DevOps

script:
  - echo "About to build and test Kitura-CouchDB for branch '$TRAVIS_BRANCH'."
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build_ubuntu.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR Kitura-CouchDB ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build_osx.sh ; fi
  - echo "Build and tests completed. See above for status."
