# Travis CI build file for Kitura-CouchDB.
# Kitura runs on OS X and Linux (Ubuntu v15.10).

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop

notifications:
  slack: ibmswift:RHkwcHYh4kkYVRVzm9nZk5TF

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
    - os: osx
      osx_image: xcode7.2
      sudo: required

before_install:
  - git submodule init
  - git submodule update
  - cd Kitura-CI && git checkout master && cd $TRAVIS_BUILD_DIR
  - git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/DevOps.git
  - git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/Kitura-TestingCredentials.git

script:
  - echo "About to build and test Kitura-CouchDB for branch '$TRAVIS_BRANCH'."
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./Kitura-CI/run_kitura_ubuntu_container.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR Kitura-CouchDB ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Kitura-CI/build_kitura_package.sh ; fi
  - echo "Build and tests completed. See above for status."
